---
environment:
  matrix:
    - nodejs_version: 9
    - nodejs_version: 8
    - nodejs_version: 6
cache:
  - "%LOCALAPPDATA%\\Yarn"
install:
  - ps: Install-Product node $env:nodejs_version x64
  - yarn
test_script:
  - yarn test --coverage
after_test:
  - ps: |
      $env:PATH = 'C:\msys64\usr\bin;' + $env:PATH
      Invoke-WebRequest -Uri 'https://codecov.io/bash' -OutFile codecov.sh
      bash codecov.sh

build: 'off'

matrix:
  fast_finish: true
