---
version: 2
jobs:
  build:
    docker:
      - image: dickeyxxx/cli-engine-docker:v1.2.1
    working_directory: /tmp/rwlockfile
    steps:
      - checkout
      - run: yarn
      - run: jest --coverage --runInBand && bash <(curl -s https://codecov.io/bash) -s coverage
      - run: flow check
      - run: standard
